global:
  resolve_timeout: 5m
  smtp_from: alertmanager@prometheus.example.com
  smtp_smarthost: mx1.example.com:25
  smtp_require_tls: false

route:
  group_by: ['alertname']
  group_wait: 10s
  group_interval: 10s
  repeat_interval: 1h
  receiver: 'blackhole'
  routes:
  - receiver: slack
    repeat_interval: 3h
    group_by:
    - alertname
    - instance
    match:
      team: release
    continue: true
  - receiver: email
    group_by:
    - alertname
    match:
      severity: log
    continue: true

receivers:
- name: 'blackhole'

- name: slack
  slack_configs:
  - send_resolved: true
    api_url: YYYYYYYYYYYYY
    channel: 'YYYYYYYYYY'
    username: Prometheus
    color: '{{ if eq .Status "firing" }}danger{{ else }}good{{ end }}'
    text: '{{ range .Alerts }}{{ .Annotations.description }} {{ end }}'
    footer: '{{ template "slack.default.footer" . }}'
    fallback: '{{ template "slack.default.fallback" . }}'
    icon_emoji: ':prometheus:'
    icon_url: '{{ template "slack.default.iconurl" . }}'

- name: email
  email_configs:
  - send_resolved: false
    to: XXX@example.com
    headers:
      From: alertmanager@prometheus.example.com
      Subject: '{{ template "email.default.subject" . }}'
      To: XXXXXXX@example.com
    html: '{{ template "email.default.html" . }}'

inhibit_rules:
  - source_match:
      severity: 'critical'
    target_match:
      severity: 'warning'
    equal: ['alertname', 'instance']

